// AUTO-GENERATED by scripts/gen-key.mjs — do not edit by hand.
// Public key that pins the extension id (safe to commit).
// Stable chrome.identity redirect URI: https://nlifpnmpnelmhdkppjpgnlhfnolofpgd.chromiumapp.org/
export const EXTENSION_KEY =
  'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu7BsFb/7fDirsow2GrQDQPaIRa02RTsDKXLsShNelKbrnjZMeJvgWepDI8oHuJiU/g03S8r2L+jB1D9R+viHgWsOf7ivP3YVUMS8axlh6bR4ci7VVfMA/r/Ox47Wd9FW+xdIWgP8tkrM3EHLfPWEfjOkAMf7FONbHXIOq/laRjrrHEFVcMGfEABwCgKhnHWhMryvCAG5VK5A7/D5tNlLVNYIZeeUsfO5g1zYCjaTroIOofMTeGJgBFnugGVLizD9a66sp08F3ufqYpmrVkz7y8MHUcjvYBWaG7bUAtZogQQ/V3cKpzuVs9IP1uutnIjFkVHdhV4ok3o5yz1+/fII1QIDAQAB'
export const EXTENSION_ID = 'nlifpnmpnelmhdkppjpgnlhfnolofpgd'
export const TWITCH_REDIRECT_URI = 'https://nlifpnmpnelmhdkppjpgnlhfnolofpgd.chromiumapp.org/'
