// Generates a stable extension key + id so the chrome.identity redirect URI is
// permanent (required to bake a Twitch Client ID and register a fixed
// "OAuth Redirect URL" in the Twitch app).
//
// Chrome derives the extension id from the manifest `key`:
//   id = first 16 bytes of SHA-256(DER public key), each hex nibble mapped 0-f -> a-p
//
// The public key is safe to commit (it only pins the id). The private key is
// written to .keys/ (gitignored) and is only needed to pack a .crx later.
import crypto from 'node:crypto'
import { writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '..')
const outFile = resolve(root, 'src/lib/extension-key.ts')

if (existsSync(outFile) && !process.argv.includes('--force')) {
  console.log('extension-key.ts already exists — pass --force to regenerate.')
  process.exit(0)
}

const { publicKey, privateKey } = crypto.generateKeyPairSync('rsa', {
  modulusLength: 2048,
  publicKeyEncoding: { type: 'spki', format: 'der' },
  privateKeyEncoding: { type: 'pkcs8', format: 'der' },
})

const keyB64 = publicKey.toString('base64')
const hash = crypto.createHash('sha256').update(publicKey).digest('hex')
const id = hash
  .slice(0, 32)
  .replace(/[0-9a-f]/g, (c) => String.fromCharCode(parseInt(c, 16) + 97))
const redirect = `https://${id}.chromiumapp.org/`

mkdirSync(resolve(root, '.keys'), { recursive: true })
writeFileSync(resolve(root, '.keys/extension-private.pkcs8.b64'), privateKey.toString('base64'))

writeFileSync(
  outFile,
  `// AUTO-GENERATED by scripts/gen-key.mjs — do not edit by hand.
// Public key that pins the extension id (safe to commit).
// Stable chrome.identity redirect URI: ${redirect}
export const EXTENSION_KEY =
  '${keyB64}'
export const EXTENSION_ID = '${id}'
export const TWITCH_REDIRECT_URI = '${redirect}'
`,
)

console.log('Extension ID :', id)
console.log('Redirect URI :', redirect)
console.log('Wrote        :', outFile)
